CREATE TABLE Triangles (
    TriangleID INTEGER,
    ObjectID INTEGER,
    Vertex1ID INTEGER,
    Vertex2ID INTEGER,
    Vertex3ID INTEGER,
    CONSTRAINT Triangles_PK PRIMARY KEY (TriangleID),
    CONSTRAINT Triangles_V1_FK FOREIGN KEY (Vertex1ID) REFERENCES Vertices(VertexID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT Triangles_V2_FK FOREIGN KEY (Vertex2ID) REFERENCES Vertices(VertexID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT Triangles_V3_FK FOREIGN KEY (Vertex3ID) REFERENCES Vertices(VertexID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT Triangles_FK FOREIGN KEY (ObjectID) REFERENCES Objects(ObjectID) ON DELETE CASCADE ON UPDATE CASCADE
);
